apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  name: pod-debugger
  namespace: default
spec:
  containers:
  - image: docker
    name: buildkit-cleaner
    command: ["sh","-c","sleep inf"]
    resources:
      limits:
        cpu: 500m
        memory: 100M
      requests:
        cpu: 10m
        memory: 100M
    volumeMounts:
    - mountPath: /host
      name: host-root
    - mountPath: /var/run 
      name: docker-sock 
  nodeName: # <NODE_NAME>
  priorityClassName: # <PRIORITY_CLASS> optional
  restartPolicy: Never
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /
      type: ""
    name: host-root
  - name: docker-sock 
    hostPath: 
      path: /var/run
